# Generated by Django 5.2.4 on 2026-08-30 08:53

import django.db.models.deletion
import parties.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pseudo', models.CharField(max_length=24, unique=True, verbose_name='pseudo')),
                ('code', models.CharField(db_index=True, default=parties.models.nouveau_code, max_length=16, unique=True, verbose_name='code de reprise')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('vu_le', models.DateTimeField(auto_now=True, verbose_name='vu le')),
                ('banni', models.BooleanField(default=False, verbose_name='exclu du classement')),
                ('nombres', models.PositiveIntegerField(default=0, verbose_name='nombres uniques')),
                ('completion', models.FloatField(default=0, verbose_name='complétion du vivier (%)')),
                ('mythiques', models.PositiveIntegerField(default=0)),
                ('legendaires', models.PositiveIntegerField(default=0)),
                ('forges', models.PositiveIntegerField(default=0, verbose_name='nombres forgés')),
                ('theoremes', models.PositiveIntegerField(default=0, verbose_name='théorèmes démontrés')),
                ('defis', models.PositiveIntegerField(default=0, verbose_name='défis validés')),
                ('tirages', models.PositiveIntegerField(default=0)),
                ('examen', models.PositiveIntegerField(default=0, verbose_name='meilleur examen')),
                ('suspect', models.CharField(blank=True, max_length=200, verbose_name='incohérence relevée')),
            ],
            options={
                'verbose_name': 'joueur',
                'verbose_name_plural': 'joueurs',
                'ordering': ['-nombres'],
            },
        ),
        migrations.CreateModel(
            name='Sauvegarde',
            fields=[
                ('joueur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sauvegarde', serialize=False, to='parties.joueur')),
                ('donnees', models.JSONField(verbose_name='état de la partie')),
                ('octets', models.PositiveIntegerField(default=0)),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='mise à jour')),
            ],
            options={
                'verbose_name': 'sauvegarde',
                'verbose_name_plural': 'sauvegardes',
            },
        ),
    ]
