# Generated by Django 5.2.4 on 2026-08-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(choices=[('bug', 'Un bug'), ('idee', 'Une idée'), ('maths', 'Une erreur mathématique'), ('equilibrage', 'Équilibrage'), ('autre', 'Autre')], max_length=16, verbose_name='objet')),
                ('message', models.TextField(max_length=2000, verbose_name='message')),
                ('page', models.CharField(blank=True, max_length=120, verbose_name='page')),
                ('version', models.CharField(blank=True, max_length=16, verbose_name='version des fichiers')),
                ('agent', models.CharField(blank=True, max_length=200, verbose_name='navigateur')),
                ('empreinte', models.CharField(blank=True, db_index=True, max_length=32, verbose_name="empreinte d'envoi")),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='reçu le')),
                ('traite', models.BooleanField(default=False, verbose_name='traité')),
                ('joueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours', to='parties.joueur', verbose_name='joueur')),
            ],
            options={
                'verbose_name': 'retour',
                'verbose_name_plural': 'retours',
                'ordering': ['-cree_le'],
            },
        ),
    ]
