# Generated by Django 5.2.4 on 2026-09-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_retour'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='calcul',
            field=models.PositiveIntegerField(default=0, verbose_name='meilleur calcul rapide'),
        ),
        migrations.AddField(
            model_name='joueur',
            name='expedition',
            field=models.PositiveIntegerField(default=0, verbose_name='couche la plus profonde'),
        ),
        migrations.AddField(
            model_name='joueur',
            name='minijeux',
            field=models.PositiveIntegerField(default=0, verbose_name='mini-jeux terminés'),
        ),
    ]
