# Generated by Django 5.2.4 on 2026-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_joueur_calcul_joueur_expedition_joueur_minijeux'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='jeux_appariement',
            field=models.PositiveIntegerField(default=0, verbose_name="parties d'Appariement"),
        ),
        migrations.AddField(
            model_name='joueur',
            name='jeux_calcul',
            field=models.PositiveIntegerField(default=0, verbose_name='parties de Calcul rapide'),
        ),
        migrations.AddField(
            model_name='joueur',
            name='jeux_expedition',
            field=models.PositiveIntegerField(default=0, verbose_name='expéditions menées'),
        ),
        migrations.AddField(
            model_name='joueur',
            name='jeux_vagues',
            field=models.PositiveIntegerField(default=0, verbose_name='parties de Vagues'),
        ),
    ]
