# Generated by Django 5.2.4 on 2026-09-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_joueur_jeux_appariement_joueur_jeux_calcul_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retour',
            name='anonyme',
            field=models.BooleanField(default=False, verbose_name='afficher en anonyme'),
        ),
        migrations.AddField(
            model_name='retour',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='publié'),
        ),
        migrations.AddField(
            model_name='retour',
            name='statut',
            field=models.CharField(choices=[('recu', 'Reçu'), ('retenu', 'Retenu'), ('fait', 'Fait'), ('refuse', 'Non retenu')], default='recu', max_length=8, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='retour',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='votes'),
        ),
        migrations.CreateModel(
            name='Voix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='donnée le')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voix', to='parties.joueur', verbose_name='joueur')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voix', to='parties.retour', verbose_name='retour')),
            ],
            options={
                'verbose_name': 'voix',
                'verbose_name_plural': 'voix',
                'constraints': [models.UniqueConstraint(fields=('retour', 'joueur'), name='une_voix_par_joueur')],
            },
        ),
    ]
