# Generated by Django 5.2.4 on 2026-09-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_retour_anonyme_retour_publie_retour_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reglages',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('version_sauvegarde', models.PositiveIntegerField(default=0, help_text="Une partie dont la version est inférieure est déclarée obsolète : le jeu propose au joueur de l'effacer. Augmentez de 1 après une refonte qui rend les anciennes parties incohérentes.", verbose_name='version de sauvegarde exigée')),
                ('maj_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'réglages',
                'verbose_name_plural': 'réglages',
            },
        ),
    ]
